import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class Dimens {
  double get one => 1.0.sp;
  double get two => 2.0.sp;
  double get three => 3.0.sp;
  double get four => 4.0.sp;
  double get five => 5.0.sp;
  double get six => 6.0.sp;
  double get seven => 7.0.sp;
  double get eight => 8.0.sp;
  double get nine => 9.0.sp;
  double get ten => 10.0.sp;
  double get eleven => 11.0.sp;
  double get twelve => 12.0.sp;
  double get thirteen => 13.0.sp;
  double get fourteen => 14.0.sp;
  double get fifteen => 15.0.sp;
  double get sixteen => 16.0.sp;
  double get seventeen => 17.0.sp;
  double get eighteen => 18.0.sp;
  double get nineteen => 19.0.sp;
  double get twenty => 20.0.sp;
  double get twentyOne => 21.0.sp;
  double get twentyTwo => 22.0.sp;
  double get twentyThree => 23.0.sp;
  double get twentyFour => 24.0.sp;
  double get twentyFive => 25.0.sp;
  double get twentySix => 26.0.sp;
  double get twentySeven => 27.0.sp;
  double get twentyEight => 28.0.sp;
  double get twentyNine => 29.0.sp;
  double get thirty => 30.0.sp;
  double get thirtyOne => 31.0.sp;
  double get thirtyTwo => 32.0.sp;
  double get thirtyThree => 33.0.sp;
  double get thirtyFour => 34.0.sp;
  double get thirtyFive => 35.0.sp;
  double get thirtySix => 36.0.sp;
  double get thirtySeven => 37.0.sp;
  double get thirtyEight => 38.0.sp;
  double get thirtyNine => 39.0.sp;
  double get forty => 40.0.sp;
  double get fortyOne => 41.0.sp;
  double get fortyTwo => 42.0.sp;
  double get fortyThree => 43.0.sp;
  double get fortyFour => 44.0.sp;
  double get fortyFive => 45.0.sp;
  double get fortySix => 46.0.sp;
  double get fortySeven => 47.0.sp;
  double get fortyEight => 48.0.sp;
  double get fortyNine => 49.0.sp;
  double get fifty => 50.0.sp;
  double get fiftyOne => 51.0.sp;
  double get fiftyTwo => 52.0.sp;
  double get fiftyThree => 53.0.sp;
  double get fiftyFour => 54.0.sp;
  double get fiftyFive => 55.0.sp;
  double get fiftySix => 56.0.sp;
  double get fiftySeven => 57.0.sp;
  double get fiftyEight => 58.0.sp;
  double get fiftyNine => 59.0.sp;
  double get sixty => 60.0.sp;
  double get sixtyOne => 61.0.sp;
  double get sixtyTwo => 62.0.sp;
  double get sixtyThree => 63.0.sp;
  double get sixtyFour => 64.0.sp;
  double get sixtyFive => 65.0.sp;
  double get sixtySix => 66.0.sp;
  double get sixtySeven => 67.0.sp;
  double get sixtyEight => 68.0.sp;
  double get sixtyNine => 69.0.sp;
  double get seventy => 70.0.sp;
  double get seventyOne => 71.0.sp;
  double get seventyTwo => 72.0.sp;
  double get seventyThree => 73.0.sp;
  double get seventyFour => 74.0.sp;
  double get seventyFive => 75.0.sp;
  double get seventySix => 76.0.sp;
  double get seventySeven => 77.0.sp;
  double get seventyEight => 78.0.sp;
  double get seventyNine => 79.0.sp;
  double get eighty => 80.0.sp;
  double get eightyOne => 81.0.sp;
  double get eightyTwo => 82.0.sp;
  double get eightyThree => 83.0.sp;
  double get eightyFour => 84.0.sp;
  double get eightyFive => 85.0.sp;
  double get eightySix => 86.0.sp;
  double get eightySeven => 87.0.sp;
  double get eightyEight => 88.0.sp;
  double get eightyNine => 89.0.sp;
  double get ninety => 90.0.sp;
  double get ninetyOne => 91.0.sp;
  double get ninetyTwo => 92.0.sp;
  double get ninetyThree => 93.0.sp;
  double get ninetyFour => 94.0.sp;
  double get ninetyFive => 95.0.sp;
  double get ninetySix => 96.0.sp;
  double get ninetySeven => 97.0.sp;
  double get ninetyEight => 98.0.sp;
  double get ninetyNine => 99.0.sp;
  double get oneHundred => 100.0.sp;
  double get oneHundredOne => 101.0.sp;
  double get oneHundredTwo => 102.0.sp;
  double get oneHundredThree => 103.0.sp;
  double get oneHundredFour => 104.0.sp;
  double get oneHundredFive => 105.0.sp;
  double get oneHundredSix => 106.0.sp;
  double get oneHundredSeven => 107.0.sp;
  double get oneHundredEight => 108.0.sp;
  double get oneHundredNine => 109.0.sp;
  double get oneHundredTen => 110.0.sp;
  double get oneHundredEleven => 111.0.sp;
  double get oneHundredTwelve => 112.0.sp;
  double get oneHundredThirteen => 113.0.sp;
  double get oneHundredFourteen => 114.0.sp;
  double get oneHundredFifteen => 115.0.sp;
  double get oneHundredSixteen => 116.0.sp;
  double get oneHundredSeventeen => 117.0.sp;
  double get oneHundredEighteen => 118.0.sp;
  double get oneHundredNineteen => 119.0.sp;
  double get oneHundredTwenty => 120.0.sp;
  double get oneHundredTwentyOne => 121.0.sp;
  double get oneHundredTwentyTwo => 122.0.sp;
  double get oneHundredTwentyThree => 123.0.sp;
  double get oneHundredTwentyFour => 124.0.sp;
  double get oneHundredTwentyFive => 125.0.sp;
  double get oneHundredTwentySix => 126.0.sp;
  double get oneHundredTwentySeven => 127.0.sp;
  double get oneHundredTwentyEight => 128.0.sp;
  double get oneHundredTwentyNine => 129.0.sp;
  double get oneHundredThirty => 130.0.sp;
  double get oneHundredThirtyOne => 131.0.sp;
  double get oneHundredThirtyTwo => 132.0.sp;
  double get oneHundredThirtyThree => 133.0.sp;
  double get oneHundredThirtyFour => 134.0.sp;
  double get oneHundredThirtyFive => 135.0.sp;
  double get oneHundredThirtySix => 136.0.sp;
  double get oneHundredThirtySeven => 137.0.sp;
  double get oneHundredThirtyEight => 138.0.sp;
  double get oneHundredThirtyNine => 139.0.sp;
  double get oneHundredForty => 140.0.sp;
  double get oneHundredFortyOne => 141.0.sp;
  double get oneHundredFortyTwo => 142.0.sp;
  double get oneHundredFortyThree => 143.0.sp;
  double get oneHundredFortyFour => 144.0.sp;
  double get oneHundredFortyFive => 145.0.sp;
  double get oneHundredFortySix => 146.0.sp;
  double get oneHundredFortySeven => 147.0.sp;
  double get oneHundredFortyEight => 148.0.sp;
  double get oneHundredFortyNine => 149.0.sp;
  double get oneHundredFifty => 150.0.sp;
  double get oneHundredFiftyOne => 151.0.sp;
  double get oneHundredFiftyTwo => 152.0.sp;
  double get oneHundredFiftyThree => 153.0.sp;
  double get oneHundredFiftyFour => 154.0.sp;
  double get oneHundredFiftyFive => 155.0.sp;
  double get oneHundredFiftySix => 156.0.sp;
  double get oneHundredFiftySeven => 157.0.sp;
  double get oneHundredFiftyEight => 158.0.sp;
  double get oneHundredFiftyNine => 159.0.sp;
  double get oneHundredSixty => 160.0.sp;
  double get oneHundredSixtyOne => 161.0.sp;
  double get oneHundredSixtyTwo => 162.0.sp;
  double get oneHundredSixtyThree => 163.0.sp;
  double get oneHundredSixtyFour => 164.0.sp;
  double get oneHundredSixtyFive => 165.0.sp;
  double get oneHundredSixtySix => 166.0.sp;
  double get oneHundredSixtySeven => 167.0.sp;
  double get oneHundredSixtyEight => 168.0.sp;
  double get oneHundredSixtyNine => 169.0.sp;
  double get oneHundredSeventy => 170.0.sp;
  double get oneHundredSeventyOne => 171.0.sp;
  double get oneHundredSeventyTwo => 172.0.sp;
  double get oneHundredSeventyThree => 173.0.sp;
  double get oneHundredSeventyFour => 174.0.sp;
  double get oneHundredSeventyFive => 175.0.sp;
  double get oneHundredSeventySix => 176.0.sp;
  double get oneHundredSeventySeven => 177.0.sp;
  double get oneHundredSeventyEight => 178.0.sp;
  double get oneHundredSeventyNine => 179.0.sp;
  double get oneHundredEighty => 180.0.sp;
  double get oneHundredEightyOne => 181.0.sp;
  double get oneHundredEightyTwo => 182.0.sp;
  double get oneHundredEightyThree => 183.0.sp;
  double get oneHundredEightyFour => 184.0.sp;
  double get oneHundredEightyFive => 185.0.sp;
  double get oneHundredEightySix => 186.0.sp;
  double get oneHundredEightySeven => 187.0.sp;
  double get oneHundredEightyEight => 188.0.sp;
  double get oneHundredEightyNine => 189.0.sp;
  double get oneHundredNinety => 190.0.sp;
  double get oneHundredNinetyOne => 191.0.sp;
  double get oneHundredNinetyTwo => 192.0.sp;
  double get oneHundredNinetyThree => 193.0.sp;
  double get oneHundredNinetyFour => 194.0.sp;
  double get oneHundredNinetyFive => 195.0.sp;
  double get oneHundredNinetySix => 196.0.sp;
  double get oneHundredNinetySeven => 197.0.sp;
  double get oneHundredNinetyEight => 198.0.sp;
  double get oneHundredNinetyNine => 199.0.sp;
  double get twoHundred => 200.0.sp;
  double get twoHundredOne => 201.0.sp;
  double get twoHundredTwo => 202.0.sp;
  double get twoHundredThree => 203.0.sp;
  double get twoHundredFour => 204.0.sp;
  double get twoHundredFive => 205.0.sp;
  double get twoHundredSix => 206.0.sp;
  double get twoHundredSeven => 207.0.sp;
  double get twoHundredEight => 208.0.sp;
  double get twoHundredNine => 209.0.sp;
  double get twoHundredTen => 210.0.sp;
  double get twoHundredEleven => 211.0.sp;
  double get twoHundredTwelve => 212.0.sp;
  double get twoHundredThirteen => 213.0.sp;
  double get twoHundredFourteen => 214.0.sp;
  double get twoHundredFifteen => 215.0.sp;
  double get twoHundredSixteen => 216.0.sp;
  double get twoHundredSeventeen => 217.0.sp;
  double get twoHundredEighteen => 218.0.sp;
  double get twoHundredNineteen => 219.0.sp;
  double get twoHundredTwenty => 220.0.sp;
  double get twoHundredTwentyOne => 221.0.sp;
  double get twoHundredTwentyTwo => 222.0.sp;
  double get twoHundredTwentyThree => 223.0.sp;
  double get twoHundredTwentyFour => 224.0.sp;
  double get twoHundredTwentyFive => 225.0.sp;
  double get twoHundredTwentySix => 226.0.sp;
  double get twoHundredTwentySeven => 227.0.sp;
  double get twoHundredTwentyEight => 228.0.sp;
  double get twoHundredTwentyNine => 229.0.sp;
  double get twoHundredThirty => 230.0.sp;
  double get twoHundredThirtyOne => 231.0.sp;
  double get twoHundredThirtyTwo => 232.0.sp;
  double get twoHundredThirtyThree => 233.0.sp;
  double get twoHundredThirtyFour => 234.0.sp;
  double get twoHundredThirtyFive => 235.0.sp;
  double get twoHundredThirtySix => 236.0.sp;
  double get twoHundredThirtySeven => 237.0.sp;
  double get twoHundredThirtyEight => 238.0.sp;
  double get twoHundredThirtyNine => 239.0.sp;
  double get twoHundredForty => 240.0.sp;
  double get twoHundredFortyOne => 241.0.sp;
  double get twoHundredFortyTwo => 242.0.sp;
  double get twoHundredFortyThree => 243.0.sp;
  double get twoHundredFortyFour => 244.0.sp;
  double get twoHundredFortyFive => 245.0.sp;
  double get twoHundredFortySix => 246.0.sp;
  double get twoHundredFortySeven => 247.0.sp;
  double get twoHundredFortyEight => 248.0.sp;
  double get twoHundredFortyNine => 249.0.sp;
  double get twoHundredFifty => 250.0.sp;
  double get twoHundredFiftyOne => 251.0.sp;
  double get twoHundredFiftyTwo => 252.0.sp;
  double get twoHundredFiftyThree => 253.0.sp;
  double get twoHundredFiftyFour => 254.0.sp;
  double get twoHundredFiftyFive => 255.0.sp;
  double get twoHundredFiftySix => 256.0.sp;
  double get twoHundredFiftySeven => 257.0.sp;
  double get twoHundredFiftyEight => 258.0.sp;
  double get twoHundredFiftyNine => 259.0.sp;
  double get twoHundredSixty => 260.0.sp;
  double get twoHundredSixtyOne => 261.0.sp;
  double get twoHundredSixtyTwo => 262.0.sp;
  double get twoHundredSixtyThree => 263.0.sp;
  double get twoHundredSixtyFour => 264.0.sp;
  double get twoHundredSixtyFive => 265.0.sp;
  double get twoHundredSixtySix => 266.0.sp;
  double get twoHundredSixtySeven => 267.0.sp;
  double get twoHundredSixtyEight => 268.0.sp;
  double get twoHundredSixtyNine => 269.0.sp;
  double get twoHundredSeventy => 270.0.sp;
  double get twoHundredSeventyOne => 271.0.sp;
  double get twoHundredSeventyTwo => 272.0.sp;
  double get twoHundredSeventyThree => 273.0.sp;
  double get twoHundredSeventyFour => 274.0.sp;
  double get twoHundredSeventyFive => 275.0.sp;
  double get twoHundredSeventySix => 276.0.sp;
  double get twoHundredSeventySeven => 277.0.sp;
  double get twoHundredSeventyEight => 278.0.sp;
  double get twoHundredSeventyNine => 279.0.sp;
  double get twoHundredEighty => 280.0.sp;
  double get twoHundredEightyOne => 281.0.sp;
  double get twoHundredEightyTwo => 282.0.sp;
  double get twoHundredEightyThree => 283.0.sp;
  double get twoHundredEightyFour => 284.0.sp;
  double get twoHundredEightyFive => 285.0.sp;
  double get twoHundredEightySix => 286.0.sp;
  double get twoHundredEightySeven => 287.0.sp;
  double get twoHundredEightyEight => 288.0.sp;
  double get twoHundredEightyNine => 289.0.sp;
  double get twoHundredNinety => 290.0.sp;
  double get twoHundredNinetyOne => 291.0.sp;
  double get twoHundredNinetyTwo => 292.0.sp;
  double get twoHundredNinetyThree => 293.0.sp;
  double get twoHundredNinetyFour => 294.0.sp;
  double get twoHundredNinetyFive => 295.0.sp;
  double get twoHundredNinetySix => 296.0.sp;
  double get twoHundredNinetySeven => 297.0.sp;
  double get twoHundredNinetyEight => 298.0.sp;
  double threeHundred = 300.sp;
  double get threeHundredFifty => 350.sp;
  double get fiveHundred => 500.0.sp;
  double get fourHundredFifty => 450.0.sp;

  EdgeInsets edgeInsetsAll(double allSide) => EdgeInsets.all(allSide);

  EdgeInsets edgeInsetsSymmetric({
    double? vertical,
    double? horizontal,
  }) =>
      EdgeInsets.symmetric(
        vertical: vertical ?? 0,
        horizontal: horizontal ?? 0,
      );

  EdgeInsets edgeInsets({
    double? left,
    double? top,
    double? right,
    double? bottom,
  }) =>
      EdgeInsets.fromLTRB(
        left ?? 0,
        top ?? 0,
        right ?? 0,
        bottom ?? 0,
      );

  Widget boxWidth(double width) => SizedBox(
        width: width,
      );
  Widget boxHeight(double height) => SizedBox(
        height: height,
      );

  /// Get the width with the percent value of the screen width.
  double percentWidth(double percentValue) => percentValue.sw;
  double percentHeght(double percentValue) => percentValue.sh;

}
