on:
  push:
    branches:
      - main
name: Code checker and Netlify deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build web
      - name: Deploy to Netlify
        uses: netlify/deploy@v1
        with:
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy-message: "Deploy from GitHub Actions"
          deploy-branch: "main"
